

CREATE DATABASE TESTE_FK;
USE TESTE_FK;

          -- EXEMPLO 1 LIVROS E LOCAÇÕES
-- TABLEA DE LIVROS

CREATE TABLE LIVROS(

        LIVRO_ID        INT(10) AUTO_INCREMENT,
        LIVRO_TITULO    VARCHAR(30) NOT NULL,
        LIVRO_SETOR     CHAR(2),
        PRIMARY KEY(LIVRO_ID)

);

-- TABELA DE LOCAÇÕES

CREATE TABLE LOCACOES(
       
        LOCACAO_ID        INT(10)  PRIMARY KEY AUTO_INCREMENT,
        LOCACAO_NOME      VARCHAR(30),
        LOCACAO_LIVRO_ID  INT(10),
        -- CHAVE ESTRANGEIRA
        -- CONSTRAINT = PK, FK, CHECK, DEFAULT, UNIQUE
        
        CONSTRAINT FK_LIVRO_ID
        FOREIGN KEY (LOCACAO_LIVRO_ID) REFERENCES LIVROS(LIVRO_ID)
        ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE BIBLIOTECA(
          
          BIBLIO_ID         INT(10) PRIMARY KEY AUTO_INCREMENT,
          BIBLIO_END_RUA    VARCHAR(40),
          BIBLIO_END_NUM    VARCHAR(6),
          BIBLIO_END_CID    VARCHAR(30)

);

  ALTER TABLE LIVROS
  ADD COLUMN LIVRO_BIBLIO_ID    INT(10),
  ADD FOREIGN KEY (LIVRO_BIBLIO_ID) REFERENCES BIBLIOTECA(BIBLIO_ID)
  ON DELETE CASCADE ON UPDATE CASCADE;

   INSERT INTO LIVROS(LIVRO_TITULO, LIVRO_SETOR)
   VALUES ('HARRY POTTER', 'B2');
   
   INSERT INTO LIVROS(LIVRO_TITULO, LIVRO_SETOR)
   VALUES ('SENHOR DOS ANEIS', 'A1');
   
   INSERT INTO LIVROS (LIVRO_TITULO, LIVRO_SETOR)
   VALUES ('A CABANA','C3');


        -- INSERINDO LOCAÇÕES PARA OS LIVROS
        
   INSERT INTO LOCACOES (LOCACAO_NOME, LOCACAO_LIVRO_ID)
   VALUE ('CHICO BENTO', 1);
   
   INSERT INTO LOCACOES (LOCACAO_NOME, LOCACAO_LIVRO_ID)
   VALUE ('MONICA', 2);
   
   INSERT INTO LOCACOES (LOCACAO_NOME, LOCACAO_LIVRO_ID)
   VALUE ('CEBOLINHA', 1);

   SELECT * FROM LOCACOES;
   SELECT * FROM LIVROS;
   



  -- EXEMPLO 2: EMPREGADOS E DEPENDENTES
  
CREATE TABLE EMPREGADOS (
		
        EMPREGADO_ID     INT(10) PRIMARY KEY AUTO_INCREMENT,
        EMPREGADO_NOME   VARCHAR(40)
        );

CREATE TABLE DEPENDENTES (
        
        DEPENDENTE_ID    INT(10),
        DEPENDENTE_NOME  VARCHAR(40),
        DEP_EMP_ID       INT(10),
        FOREIGN KEY (DEP_EMP_ID) REFERENCES EMPREGADOS(EMPREGADO_ID)
        ON DELETE CASCADE ON UPDATE CASCADE

);

  -- EXEMPLO 3 PEDIDOS E INTENS_PEDIDO
  
  CREATE TABLE PEDIDOS(
  
       PEDIDO_NUM         INT(10) PRIMARY KEY AUTO_INCREMENT,
       PEDIDO_DATA        DATETIME
       
       );
       
  CREATE TABLE ITENS_PEDIDO(
       
       ITEM_PED_ID      INT(10)  AUTO_INCREMENT,
       ITEM_PED_NUM     INT(10),
       ITEM_PED_QTD     INT(10),

       PRIMARY KEY (ITEM_PED_ID, ITEM_PED_NUM),
       FOREIGN KEY (ITEM_PED_NUM) REFERENCES PEDIDOS(PEDIDO_NUM)
       ON DELETE CASCADE ON UPDATE CASCADE
);
       

        
        
        
        
        
        
        
        
        
        