CREATE DATABASE aula;

USE AULA;

CREATE TABLE ANIMAL (

    ANIMAL_COD      INT  (5),
    ANIMAL_NOME     CHAR (20)
 );

   
   INSERT INTO ANIMAL (ANIMAL_COD, ANIMAL_NOME)
   VALUES (1, 'GATO');
   
   INSERT INTO ANIMAL (ANIMAL_COD, ANIMAL_NOME)
   VALUES (2, 'CACCHORRO');
   
   INSERT INTO ANIMAL (ANIMAL_COD, ANIMAL_NOME)
   VALUES (3, 'PAPAGAIO');
   
   INSERT INTO ANIMAL (ANIMAL_COD, ANIMAL_NOME)
   VALUES (4, 'PASSAROS');
   
   INSERT INTO ANIMAL (ANIMAL_COD, ANIMAL_NOME)
   VALUES (5, 'TARTARUGA');
   
   INSERT INTO ANIMAL (ANIMAL_COD, ANIMAL_NOME)
   VALUES (6, 'COBRA');
   
   INSERT INTO ANIMAL (ANIMAL_COD, ANIMAL_NOME)
   VALUES (7, 'CAVALO');
   
   INSERT INTO ANIMAL (ANIMAL_COD, ANIMAL_NOME)
   VALUES (8, 'LAGARTO');
   
   INSERT INTO ANIMAL (ANIMAL_COD, ANIMAL_NOME)
   VALUES (9, 'ELEFANTE');
   
   INSERT INTO ANIMAL (ANIMAL_COD, ANIMAL_NOME)
   VALUES (10, 'ZEBRA');
   
   
   CREATE TABLE FUNCIONARIO (
   
   FUNC_COD       INT     (6),
   FUNC_NOME      CHAR    (30),
   FUNC_SALA      DECIMAL (10,2)  -- SALÁRIO
   
   );
    
    INSERT INTO FUNCIONARIO (FUNC_COD, FUNC_NOME, FUNC_SALA)
    VALUES (1, 'MARIA AMÉLIA', 1500.23);  
    
    INSERT INTO FUNCIONARIO (FUNC_COD, FUNC_NOME, FUNC_SALA)
    VALUES (2, 'ÂNGELA PEREIRA', 2500.29);
    
    INSERT INTO FUNCIONARIO (FUNC_COD, FUNC_NOME, FUNC_SALA)
    VALUES (3, 'SONIA DUARTE', 980.23);
    
    INSERT INTO FUNCIONARIO (FUNC_COD, FUNC_NOME, FUNC_SALA)
    VALUES (4, 'PAULO PEREIRA', 325.63);
    
    INSERT INTO FUNCIONARIO (FUNC_COD, FUNC_NOME, FUNC_SALA)
    VALUES (5, 'RUTH ROCHA', 452.26);
    
    INSERT INTO FUNCIONARIO (FUNC_COD, FUNC_NOME, FUNC_SALA)
    VALUES (6, 'RAQUEL REGUETE', 586.59);
    
    INSERT INTO FUNCIONARIO (FUNC_COD, FUNC_NOME, FUNC_SALA)
    VALUES (7, 'SANDRA SODRÉ', 458.26);
    
    INSERT INTO FUNCIONARIO (FUNC_COD, FUNC_NOME, FUNC_SALA)
    VALUES (8, 'TÂNIA TAMARA', 875.26);
    
    INSERT INTO FUNCIONARIO (FUNC_COD, FUNC_NOME, FUNC_SALA)
    VALUES (9, 'PEDRO PAULO PEREIRA', 2326.25);
    
    INSERT INTO FUNCIONARIO (FUNC_COD, FUNC_NOME, FUNC_SALA)
    VALUES (10, 'GERALDO GALHARDO', 1253.26);
   
    
    CREATE TABLE PROFESSOR ( 
    
    PROF_COD         INT     (6),
    PROF_NOME        CHAR    (30),
    PROF_SEXO        CHAR    (1),
    PROF_SALA        DECIMAL (10,2),
    PROF_DATACAD     DATE         -- DATA DE CADASTRO
    
    );
    
    
     INSERT INTO PROFESSOR (PROF_COD, PROF_NOME, PROF_SEXO, PROF_SALA, PROF_DATACAD)
     VALUES (1, 'ANDRÉ EIRA', 'M', 2562.23, '2008-1-2');
    
     INSERT INTO PROFESSOR (PROF_COD, PROF_NOME, PROF_SEXO, PROF_SALA, PROF_DATACAD)
     VALUES (2, 'JOSÉ PEREIRA', 'M', 2546.25, '2009-2-1');
    
     INSERT INTO PROFESSOR (PROF_COD, PROF_NOME, PROF_SEXO, PROF_SALA, PROF_DATACAD)
     VALUES (3, 'MANOEL BEIRA', 'M', 2584.26, '2010-2-3');
    
     INSERT INTO PROFESSOR (PROF_COD, PROF_NOME, PROF_SEXO, PROF_SALA, PROF_DATACAD)
     VALUES (4, 'ANTONIO PEREIRA', 'M', 1526.58, '2010-3-3');
    
     INSERT INTO PROFESSOR (PROF_COD, PROF_NOME, PROF_SEXO, PROF_SALA, PROF_DATACAD)
     VALUES (5, 'VALÉRIA ZOEIRA', 'F', 4526.23, '2010-3-4');
    
     INSERT INTO PROFESSOR (PROF_COD, PROF_NOME, PROF_SEXO, PROF_SALA, PROF_DATACAD)
     VALUES (6, 'VAGNER AMOREIRA', 'M', 235.26, '2010-4-1');
    
     INSERT INTO PROFESSOR (PROF_COD, PROF_NOME, PROF_SEXO, PROF_SALA, PROF_DATACAD)
     VALUES (7, 'VALMOR BANANEIRA', 'M', 125.62, '2011-5-5');
    
     INSERT INTO PROFESSOR (PROF_COD, PROF_NOME, PROF_SEXO, PROF_SALA, PROF_DATACAD)
     VALUES (8, 'ARLETE GARIBEIRA', 'F', 154.26, '2011-6-6');
    
     INSERT INTO PROFESSOR (PROF_COD, PROF_NOME, PROF_SEXO, PROF_SALA, PROF_DATACAD)
     VALUES (9, 'JOANETE MACIEIRA', 'F', 1485.25, '2012-7-7');
    
     INSERT INTO PROFESSOR (PROF_COD, PROF_NOME, PROF_SEXO, PROF_SALA, PROF_DATACAD)
     VALUES (10, 'CLAUDETE GALOPEIRA', 'F', 2587.13, '2012-8-8');
   
   
     SELECT * FROM PROFESSOR                    -- PARA VIZUALIZAR
     SELECT * FROM FUNCIONARIO
     SELECT * FROM ANIMAL
     
     
   
   
   
   
   
   
   
   
   
   
   