

   CREATE DATABASE PEDIDOS_VENDA
     
     USE PEDIDOS_VENDA;
     
     CREATE TABLE PRODUTOS (
     
     PRODUTO_COD                INT(6),
     PRODUTO_NOME               VARCHAR(30),
     PRODUTO_COD_UNI_MED        INT(6),                         -- UNIDADE DE MEDIDA
     PRODUTO_COD_CAT            INT(6),
     PRODUTO_QNTD_ESTOQUE       INT(8),
     PRODUTO_QNT_MINIMA         INT(3),	
     PRODUTO_PREÇO_CUSTO        DECIMAL(7,2),
     PRODUTO_PREÇO_VENDA        DECIMAL(7,2),
     PRODUTOS_CARA_TEC          VARCHAR(40)                    -- CARACTERÍSTICAS TÉCNICAS
     
     );
     
     
     CREATE TABLE UNIDADES (
      
      UNIDADE_COD          INT(6) PRIMARY KEY AUTO_INCREMENT,
      UNIDADE_NOME         VARCHAR(8)
	
    );
    
    INSERT INTO UNIDADES (UNIDADE_COD, UNIDADE_NOME)
    VALUES (1, 'PECAS');
    
    INSERT INTO UNIDADES (UNIDADE_COD, UNIDADE_NOME)
    VALUES (2, 'METROS');
    
    INSERT INTO UNIDADES (UNIDADE_COD, UNIDADE_NOME)
    VALUES (3, 'QUILOGRAMAS');
    
    INSERT INTO UNIDADES (UNIDADE_COD, UNIDADE_NOME)
    VALUES (4, 'DUZIAS');
    
    INSERT INTO UNIDADES (UNIDADE_COD, UNIDADE_NOME)
    VALUES (5,'PACOTE');
    
    INSERT INTO UNIDADES (UNIDADE_COD, UNIDADE_NOME)
    VALUES (6, 'CAIXA');
    
    
    
    CREATE TABLE CATEGORIAS (
    
    CATEGORIA_COD         INT(6)       PRIMARY KEY AUTO_INCREMENT,
    CATEGORIA_NOME        VARCHAR(20)
    
    );  
     
     
	INSERT INTO CATEGORIAS (CATEGORIA_COD, CATEGORIA_NOME)
    VALUES (1, 'MOUSE');
    
    INSERT INTO CATEGORIAS (CATEGORIA_COD, CATEGORIA_NOME)
    VALUES (2, 'PEN-DRIVE');
    
    INSERT INTO CATEGORIAS (CATEGORIA_COD, CATEGORIA_NOME)
    VALUES (3, 'MONITOR_DE_VIDEO');
    
    INSERT INTO CATEGORIAS (CATEGORIA_COD, CATEGORIA_NOME)
    VALUES (4,'TECLADO');
    
    INSERT INTO CATEGORIAS (CATEGORIA_COD, CATEGORIA_NOME)
    VALUES (5, 'CPU');
    
    INSERT INTO CATEGORIAS (CATEGORIA_COD, CATEGORIA_NOME)
    VALUES (6, 'CABO_DE_REDE');
    
    
    CREATE TABLE CLIENTES (
    
    CLIENTE_COD      INT(6),
    CLIENTE_NOME     VARCHAR(40),
    CLIENTE_RG       VARCHAR(14),
    CLIENTE_CPF      VARCHAR(15)
    
    );
    
    
    CREATE TABLE CONTATO (
    
    CONTATO_TELEFONE       VARCHAR(15),
    CONTATO_EMAIL          VARCHAR(25),
    CONTATO_FAX            INT(10)

    );
    
    
    
    CREATE TABLE VENDEDORES (
    
    VENDEDOR_COD          INT(6),
    VENDEDOR_NOME         INT(40),
    VENDEDOR_RG           VARCHAR(15),
    VENDEDOR_CPF          VARCHAR(14),
    VENDEDOR_EMAIL        VARCHAR(25),
    VENDEDOR_TELEFONE     VARCHAR(15)

    );
    
    
    
    CREATE TABLE PEDIDOS (
    
    PEDIDO_NUM            INT(7)    PRIMARY KEY AUTO_INCREMENT,
    PEDIDO_COD_CLIENTE    INT(7),
    PEDIDO_COD_VENDEDOR   INT(7),
    PEDIDO_DATA_EMISSAO   DATETIME,
    PEDIDO_DATA_ENTREGA   DATETIME,
    PEDIDO_VALOR_TOTAL    DECIMAL(10,2),
    PEDIDO_SITUACAO       CHAR(1),               --  P para PENDENTE; C para CANCELADO; E para ENTREGUE
    PEDIDO_OBSERVAÇÃO     VARCHAR(50)
    
    );
    
    CREATE TABLE ITENS_PEDIDO (
    
    ITEN_NUMERO_PEDIDO    INT(7),
    ITEN_NUMERO           INT(7),
    ITEN_CODIGO_PRODUTO   INT(7),
    ITEN_QUANTIDADE       INT(15),
    ITEN_PREÇO_UNITARIO   DECIMAL(6,2),
    ITEN_DESCONTO_        DECIMAL(6,2)
    
    );
    
    
    
    
    

    
    
    
    
    
    